baseURL = 'https://dr-tc.github.io/uu-campus-quest/'
languageCode = 'en-us'
title = 'UU Campus Quest'
theme = 'PaperMod'
[params]
defaultTheme = "dark"


[params.assets]
favicon = "/favicon.ico"


[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 10
[[menu.main]]
  name = 'Explorers Trail'
  url = '/explorers-trail'
  weight = 15

[[menu.main]]
  name = 'About'
  url = '/about'
  weight = 25


